version: '3.9'
services: 
    servercreator:
        image: servercreator
#        depends_on:
#            - db
        volumes: 
            - ./project/:/environment
        networks:
            - internal

#    db:
#        image: postgres
#        restart: always
#        environment:
#            POSTGRES_PASSWORD: example
#        networks: 
#            - internal
networks:
    internal:

        


