version: '3.9'
services: 
    servercreator:
        image: servercreator
        depends_on:
            - db
        volumes: 
            - ./project:/enviroment
        networks:
            - internal
        stdin_open: true # docker run -i
        tty: true 
 

    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: Mv3qCSJwMkRr9FPzTsRehc5MxewQYC9
            POSTGRES_DB: backend

        networks: 
            - internal
networks:
    internal:

        


